<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

use CodeIgniter\I18n\Time;

class KomikMangaSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                "judul" => "Naruto",
                "slug" => "naruto",
                "penulis" => "Masashi Kishimoto",
                "sampul" => "https://images-na.ssl-images-amazon.com/images/I/51FZVjMaFPL._SX331_BO1,204,203,200_.jpg",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => "Sebelum kelahiran Naruto, rubah setan besar telah menyerang Desa Konoha. Hokage ke-4 dari desa konoha menyegel iblis di dalam Naruto yang baru lahir, menyebabkan dia tumbuh dibenci oleh sesama penduduk desa. Meskipun kurangnya bakat di banyak bidang ninjutsu, Naruto berusaha untuk hanya satu tujuan: untuk mendapatkan gelar Hokage, ninja terkuat di desanya. Menginginkan rasa hormat yang tidak pernah dia terima, Naruto bekerja menuju mimpinya dengan teman-teman Sasuke dan Sakura dan gurunya Kakashi saat mereka melalui banyak cobaan dan pertempuran yang datang dengan menjadi seorang ninja.",
                "tahun_rilis" => "1999",
                "penerbit" => "Shounen Jump",
                "rating" => "9.10",
                "status" => "Tamat"
            ],
            [
                "judul" => "One Piece",
                "slug" => "one-piece",
                "penulis" => "Eiichiro Oda",
                "sampul" => "https://m.media-amazon.com/images/M/MV5BMWEyYzRmZTItYTllMC00ZGYzLWE3MjMtYjBkN2E5MmNmY2Q5XkEyXkFqcGdeQXVyNjkyODgxMDM@._V1_.jpg",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => "One Piece berpusat pada seorang anak muda yang bernama Monkey D. Luffy dengan tekatnya yakni menjadi bajak laut terhebat. Luffy memiliki cita-cita sebagai bajak laut karena terinspirasi dari seorang bajak laut bernama Shanks. Shanks mengarungi samudera untuk mencari harga karun legendaris yakni One Piece yang ditinggalkan oleh raja bajak laut Gol D. Roger. Luffy kemudian berpetualang di penjuru lautan hingga satu persatu dia bertemu dengan teman dan awak barunya. Bagaimanakah kelanjutan dari Komik OP ini?",
                "tahun_rilis" => "1997",
                "penerbit" => "Shounen Jump",
                "rating" => "9.78",
                "status" => "Tamat"
            ],
            [
                "judul" => "Ao no Exorcist",
                "slug" => "ao-no-exorcist",
                "penulis" => "Kazue Katou",
                "sampul" => "https://64.media.tumblr.com/f0be2fef0f05f3796392ef13dd209f48/da165216f427ad09-5f/s640x960/0518237e3facc72c3f69e71882e638116762ca55.jpg",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => "Dunia ini terbagi menjadi dua dimensi yang menjadi satu, Yang pertama adalah dunia Manusia Assiah dan lainnya adalah dunia Iblis Gehenna, Melintasi dan menyentuh antar dua dunia adalah hal yang mustahil, Tapi dengan kekuatannya Satan bisa bisa melewati dan bahkan membawa seluruh isi dunia Iblis bersamanya, Tetapi ada satu hal yang Satan tak punya, Tubuh fisik yang bisa menahannya, untuk itulah ia menciptakan Rin, Akankah Rin setuju tubuhnya digunakan atau bahkan balik mengusir Satan?",
                "tahun_rilis" => "2009",
                "penerbit" => "Jump SQ",
                "rating" => "9.05",
                "status" => "Belum Tamat"
            ],
            [
                "judul" => "Rising x Rydeen",
                "slug" => "rising-x-rydeen",
                "penulis" => "Fukuhara Renji & Hatsumi Youichi",
                "sampul" => "https://cdn.myanimelist.net/images/manga/1/179595l.jpg",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => 'Shimonone Takara, seorang pemuda, aneh, dan sehat, selalu ingin menjadi "Stranger", seseorang yang memiliki kekuatan luar biasa. Suatu hari, Takara bertemu dengan seorang wanita bernama Aria yang tergabung dalam sebuah organisasi. Apa yang dia inginkan darinya? Apakah Takara berhasil menjadi makhluk yang "aneh"?',
                "tahun_rilis" => "2012",
                "penerbit" => "N/A",
                "rating" => "6.0",
                "status" => "Tamat"
            ],
            [
                "judul" => "Kemono Giga",
                "slug" => "kemono-giga",
                "penulis" => "Koishi Chikasa",
                "sampul" => "https://mangacv.com/wp-content/uploads/cover-261.jpg",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => "Yuu adalah anak laki-laki dengan nasib buruk. Ada banyak sekali insiden di mana orang disandera, diperas, atau terlibat dalam kecelakaan lalu lintas dalam rentang waktu seminggu atau sebulan. Kejadian seperti itu terjadi saat Yuu diculik, seperti biasa, dalam perjalanannya untuk dipindahkan ke sekolah lain. Para lizardmen, bawa Yuu bersama mereka ke saluran air bawah tanah. Yuu ketakutan dan putus asa untuk melarikan diri, tapi kemudian seorang gadis muncul untuk menyelamatkannya. Gadis itu adalah gadis kucing non-manusia yang dapat mengontrol kekuatan listrik dan dia mencoba untuk menyelamatkan Yuu, tetapi kemudian sebuah insiden terjadi! Munculnya musuh yang sangat berbahaya dan merepotkan, yang dikenal sebagai “Makatsuhi” (マ カ ツ ヒ), yaitu monster yang akan menyerang dan membunuh siapa saja! Yuu mencoba melarikan diri ketika gadis itu pergi melawan Makatsuhi sendirian, tetapi kemudian dia memperkuat tekadnya dan pergi untuk mencoba menyelamatkannya, dan setelah pertemuan ini hidupnya berubah.",
                "tahun_rilis" => "2018",
                "penerbit" => "-",
                "rating" => "7.0",
                "status" => "Belum Tamat"
            ],
            [
                "judul" => "Shuumatsu no Valkyrie",
                "slug" => "shuumatsu-no-valkyrie",
                "penulis" => "Fukui, Takumi (Story) | Umemura, Shinya (Story) | Ajichika (Art)",
                "sampul" => "https://i.pinimg.com/originals/b9/28/dd/b928dd2e916ace8a36240902ebb8a24f.jpg",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => "13 manusia terhebat dalam sejarah umat manusia akan melawan 13 dewa untuk menentukan nasib umat manusia apakah akan dimusnahkan atau tetap dibiarkan hidup dalam pertarungan ragnarok satu lawan satu antara manusia dengan dewa. Bagaimanakah hasil pertarungannya?",
                "tahun_rilis" => "2017",
                "penerbit" => "Comic Zenon",
                "rating" => "9.13",
                "status" => "Belum Tamat"
            ],
            [
                "judul" => "Monster x Monster",
                "slug" => "monster-x-monster",
                "penulis" => "Tobita Nikiichi",
                "sampul" => "https://external-preview.redd.it/RlUFeCzbConqY4ntQEZww6aliF1IaYOplVmuHVL7g6s.jpg?width=640&crop=smart&auto=webp&s=5c70b3feb53ae14c3761910fbc01d5dd4f518671",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => 'Dahulu kala, dunia ini dikuasai oleh binatang buas. Manusia tidak lagi duduk di atas rantai makanan, mereka adalah mangsa monster. Namun, Mereka yang akan melawan monster berkumpul bersama dan mereka terus bertarung melawan monster untuk bertahan hidup melawan aturan mereka. Sejak itu, ratusan tahun telah berlalu ... dan sekarang "pertarungan" melawan monster telah menjadi "perburuan" untuk monster. ',
                "tahun_rilis" => "2014",
                "penerbit" => "Manga One (Shogakukan), Shounen Sunday S (Shogakukan)",
                "rating" => "7.48",
                "status" => "Tamat"
            ],
            [
                "judul" => "Boruto",
                "slug" => "boruto",
                "penulis" => "Kodachi & Ukyou",
                "sampul" => "https://dwgkfo5b3odmw.cloudfront.net/manga/thumbs/shonenjump/boruto/boruto58R/thumb_web-Frqtz9ypOrd1EYHF9XLSvA.jpg",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => 'Manga Boruto/Komik Boruto The Next Generation pertama kali terbit pada 9 Mei 2016 dikarang oleh Kodachi & Ukyou merupakan manga lanjutan dari serial terkenal yakni Naruto yang tamat beberapa saat lalu. Berdasarkan plot ceritanya komik boruto berpusat pada seorang anak kecil yang bernama Uzumaki Boruto, anak dari Uzumaki Naruto. Dia merupakan anak yang nakal dan memiliki kepribadian yang agak mirip dengan ayahnya. Bagaiamanakah perjalanan karir Ninja Boruto? Apakah dia dapat melampaui ayahnya yang telah menjadi Hokage? Yuk dibaca aja Komik Boruto Bahasa Indonesia terbaru hanya di otakuindo.net',
                "tahun_rilis" => "2016",
                "penerbit" => "Shounen Jump",
                "rating" => "9.31",
                "status" => "Belum Tamat"
            ],
            [
                "judul" => "One Punch Man",
                "slug" => "one-punch-man",
                "penulis" => "Yusuke Murata & ONE",
                "sampul" => "https://m.media-amazon.com/images/M/MV5BMTNmZDE2NDEtNTg3MS00OTE1LThlZGUtOGZkZTg0NTUyNGVmXkEyXkFqcGdeQXVyNTgyNTA4MjM@._V1_.jpg",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => 'Manga One Punch Man merupakan komik yang dibuat ulang dari judul komik yang sama, One punch-man terbit pertama kali pada tanggal 14 Juni 2012 yang sekarang digambar oleh Yusuke Murata. Cerita pada serial ini berpusat pada seseorang pemuda bernama Saitama yang menjadi pahlawan sebagai hobinya. Setelah berlatih 100 kali push-up, 100 kali sit-up dan 100 kali squats, akhirnya Saitama mendapatkan kekuatan yang tak terkalahkan hingga di setiap pertarungannya selalu berakhir dengan satu pukulan.',
                "tahun_rilis" => "2012",
                "penerbit" => "Tonari no Young Jump",
                "rating" => "9.30",
                "status" => "Belum Tamat"
            ],
            [
                "judul" => "Tokyo Ghoul",
                "slug" => "tokyo-ghoul",
                "penulis" => "Ishida Sui",
                "sampul" => "https://www.barnesandnoble.com/blog/sci-fi-fantasy/wp-content/uploads/sites/4/2017/10/TokyoGhoulMonster.jpg",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => "Pembunuhan aneh sedang terjadi di Tokyo. Karena bukti cair di tempat kejadian, polisi menyimpulkan serangan tersebut adalah hasil dari hantu jenis 'pemakan'. Teman kuliah Kaneki dan Hide muncul dengan gagasan bahwa hantu meniru manusia jadi itu sebabnya mereka belum pernah melihatnya. Sedikit yang mereka ketahui bahwa teori mereka mungkin akan menjadi kenyataan.",
                "tahun_rilis" => "2011",
                "penerbit" => "Miracle Jump (Shueisha), Shuukan Young Jump (Shueisha)",
                "rating" => "8.35",
                "status" => "Tamat"
            ],
            [
                "judul" => "World Trigger",
                "slug" => "world-trigger",
                "penulis" => "Ashihara, Daisuke (Story & Art)",
                "sampul" => "https://cdn.myanimelist.net/s/common/uploaded_files/1576903132-e8e56e988ca6b55bfc592855529f2094.jpeg",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => "Bumi berada di bawah ancaman konstan dari Tetangga, monster tak terkalahkan dari dimensi lain yang menghancurkan cara hidup kita. Setidaknya kita memiliki prajurit elit Border, yang mengkooptasi teknologi alien untuk melawan! Pahlawan kita, Osamu Mikumo mungkin bukan agen terbaik, tetapi dia akan melakukan apa pun untuk mempertahankan kehidupan di Bumi seperti yang kita ketahui. Ketika Osamu bertemu dengan humanoid Neighbor yang penuh semangat bernama Yuma, semua yang menurutnya benar dihidupkan kepalanya. Bisakah kedua musuh alami itu menjadi teman?",
                "tahun_rilis" => "2013",
                "penerbit" => "Jump SQ",
                "rating" => "8.25",
                "status" => "Tamat"
            ],
            [
                "judul" => "Black Clover",
                "slug" => "black-clover",
                "penulis" => "Tabata & Yuuki",
                "sampul" => "https://dw9to29mmj727.cloudfront.net/products/1421595176.jpg",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => "Bumi berada di bawah ancaman konstan dari Tetangga, monster tak terkalahkan dari dimensi lain yang menghancurkan cara hidup kita. Setidaknya kita memiliki prajurit elit Border, yang mengkooptasi teknologi alien untuk melawan! Pahlawan kita, Osamu Mikumo mungkin bukan agen terbaik, tetapi dia akan melakukan apa pun untuk mempertahankan kehidupan di Bumi seperti yang kita ketahui. Ketika Osamu bertemu dengan humanoid Neighbor yang penuh semangat bernama Yuma, semua yang menurutnya benar dihidupkan kepalanya. Bisakah kedua musuh alami itu menjadi teman?",
                "tahun_rilis" => "2015",
                "penerbit" => "Shuukan Shounen Jump",
                "rating" => "9.43",
                "status" => "Belum Tamat"
            ],
            [
                "judul" => "Kokoro Irozuku Koi ga",
                "slug" => "kokoro-irozuku-koi-ga-shitai",
                "penulis" => "Minori Chigusa",
                "sampul" => "https://cover.komiku.id/wp-content/uploads/2021/04/Manga-Kokoro-Irozuku-Koi-ga-Shitai.jpg?w=225&quality=60",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => "Bercerita tentang Komedi romantis penuh warna dengan heroin-heroin cantik.",
                "tahun_rilis" => "2021",
                "penerbit" => "N/A",
                "rating" => "6.5",
                "status" => "Belum Tamat"
            ],
            [
                "judul" => "Bleach",
                "slug" => "bleach",
                "penulis" => "Kubo Tite",
                "sampul" => "https://cdn.myanimelist.net/images/manga/2/180089.jpg",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => "Ichigo Kurosaki selalu bisa melihat hantu, tapi kemampuan ini tidak mengubah hidupnya sebanyak pertemuan dekatnya dengan Rukia Kuchiki, seorang Soul Reaper dan anggota Soul Society yang misterius. Saat melawan Hollow, roh jahat yang memangsa manusia yang menampilkan energi psikis, Rukia mencoba untuk meminjamkan Ichigo beberapa kekuatannya sehingga dia dapat menyelamatkan keluarganya, tetapi sangat mengejutkan, Ichigo menyerap setiap tetes energinya. Sekarang menjadi Soul Reaper sendiri, Ichigo dengan cepat mengetahui bahwa dunia yang dia tinggali adalah dunia yang penuh dengan roh berbahaya, dan bersama dengan Rukia, yang perlahan mendapatkan kembali kekuatannya, itu tugas Ichigo untuk melindungi orang yang tidak bersalah dari Hollow dan membantu roh sendiri menemukan kedamaian.",
                "tahun_rilis" => "2000",
                "penerbit" => "Akamaru Jump, Shuukan Shounen Jump",
                "rating" => "7.59",
                "status" => "Tamat"
            ],
            [
                "judul" => "The Revenge of the Soul Eater",
                "slug" => "the-revenge-of-the-soul-eater",
                "penulis" => "Gyokuto, Toujou Chika",
                "sampul" => "https://cover.komiku.id/wp-content/uploads/2021/03/Manga-The-Revenge-of-the-Soul-Eater.jpg?w=225&quality=60",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => "Rumah tangga Mitsurugi diberi tugas penting untuk menjaga gerbang iblis oleh kaisar. Mitsurugi Sora, yang merupakan pewaris keluarga, dipanggil untuk mengikuti upacara persidangan pada usia tiga belas tahun. Dia harus mengatasi cobaan untuk mempelajari gaya pedang hantu yang diwariskan oleh keluarga Mitsurugi dari generasi ke generasi. Tujuh siswa lainnya pada usia yang sama yang telah mengikuti persidangan semuanya telah lulus. Dan sekarang hanya Sora yang tersisa. Ayahnya, saudara laki-laki, tunangannya, dan sepasang saudara kandung yang telah mengawasinya semuanya melihat, saat upacara persidangan Sora dimulai dengan sungguh-sungguh…",
                "tahun_rilis" => "2020",
                "penerbit" => "N/A",
                "rating" => "6.2",
                "status" => "Belum Tamat"
            ],
            [
                "judul" => "Juujika no Rokunin",
                "slug" => "juujika-no-rokunin",
                "penulis" => "Nakatake Shiryuu",
                "sampul" => "https://cover.komiku.id/wp-content/uploads/2020/09/Manga-Juujika-no-Rokunin.jpg?w=225&quality=60",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => '"Apakah saya tetap bisa membunuh orang?" Ketegangan balas dendam yang berbahaya oleh Shiryu Nakatake, pendatang baru di Majalah Bessatsu Shonen. "Hindari, jika seseorang bertobat, biarkan dia pergi dan tidak melakukan apa-apa. Dia harus diberi kesempatan untuk dilahirkan kembali." "Kakek, kuharap dia tidak bereinkarnasi sendiri." Untuk mengalahkan beberapa monster non-manusia, bocah itu juga menjadi sesuatu yang bukan manusia. Shun Uruma, seorang siswa kelas enam, dinamai "Tubuh Eksperimental: A" oleh lima teman sekelasnya dan diintimidasi secara parah dan tinggal di neraka. Satu-satunya kedamaian adalah dengan saudaranya, yang mencintainya, dan orang tuanya, yang melindunginya ..... sampai lima monster membunuh keluarganya. Ketika dia akhirnya kehilangan segalanya dan menghadapi neraka yang sebenarnya, sebuah "keinginan" gelap lahir di dalam Shun. Dia terlahir kembali di bawah pelatihan kakeknya, yang bertugas di unit rahasia selama Perang Dunia II. Sekarang, empat tahun kemudian, dia muncul di depan musuh yang ditakdirkannya. "Aku tidak akan membiarkan SIAPA PUN menghalangi pembalasanku."',
                "tahun_rilis" => "2020",
                "penerbit" => "Bessatsu Shounen Magazine (Kodansha)",
                "rating" => "6.59",
                "status" => "Belum Tamat"
            ],
            [
                "judul" => "Radiant",
                "slug" => "radiant",
                "penulis" => "Tony Valente",
                "sampul" => "https://cdn.myanimelist.net/images/anime/1974/108398.jpg",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => 'Seth adalah calon penyihir dari daerah Pompo Hills. Seperti semua penyihir, ia adalah “terinfeksi”: salah satu dari sedikit makhluk hidup yang selamat dari kontak Nemesis, makhluk-makhluk ini jatuh dari langit yang mencemari dan memusnahkan semua yang mereka sentuh.',
                "tahun_rilis" => "2013",
                "penerbit" => "N/A",
                "rating" => "7.02",
                "status" => "Belum Tamat"
            ],
            [
                "judul" => "Colorless",
                "slug" => "colorless",
                "penulis" => "KENT",
                "sampul" => "https://i.pinimg.com/236x/66/49/b9/6649b9ad96a6718d2bedc0d8eb0bec09.jpg",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => 'Sebuah Gelombang Matahari besar menyebabkan bumi kehilangan semua warnanya. Manusia berubah bentuk dan jumlahnya berkurang drastis. Kunci untuk memulihkan dunia yang dulu ada pada kekuatan tersembunyi di dalam 「warna」, dan seorang 「gadis」. Mengetahui bahwa sisa-sia warna di bumi memiliki kekuatan yang besar, Avidia, yang sedang melakukan penyelidikan sembari melindungi seorang gadis bernama Chie, memakai warna untuk mengembangkan kekuatannya sendiri, dan melemparkan dirinya ke dalam peperangan dengan para kultus.',
                "tahun_rilis" => "2020",
                "penerbit" => "-",
                "rating" => "7.0",
                "status" => "Belum Tamat"
            ],
            [
                "judul" => "Nidome no Jinsei wo Isekai de",
                "slug" => "nidome-no-jinsei-wo-isekai-de",
                "penulis" => "Main & Abo Satoru",
                "sampul" => "https://cdn.myanimelist.net/images/manga/1/186026.jpg",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => 'Sebuah Gelombang Matahari besar menyebabkan bumi kehilangan semua warnanya. Manusia berubah bentuk dan jumlahnya berkurang drastis. Kunci untuk memulihkan dunia yang dulu ada pada kekuatan tersembunyi di dalam 「warna」, dan seorang 「gadis」. Mengetahui bahwa sisa-sia warna di bumi memiliki kekuatan yang besar, Avidia, yang sedang melakukan penyelidikan sembari melindungi seorang gadis bernama Chie, memakai warna untuk mengembangkan kekuatannya sendiri, dan melemparkan dirinya ke dalam peperangan dengan para kultus.',
                "tahun_rilis" => "2016",
                "penerbit" => "N/A",
                "rating" => "7.1",
                "status" => "Belum Tamat"
            ],
            [
                "judul" => "Blood Lad",
                "slug" => "blood-lad",
                "penulis" => "Kodama Yuuki",
                "sampul" => "https://cover.komiku.id/wp-content/uploads/2020/09/Manga-Blood-Lad.jpg?w=225&quality=60",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => 'Vampir Staz adalah salah satu bos distrik paling kuat di dunia iblis, menangkis semua orang yang berani menantangnya. Tapi diam-diam, Staz yang menakutkan terobsesi dengan budaya manusia, terutama video game, manga, dan segala sesuatu yang berasal dari Jepang! Ketika seorang gadis Jepang mengembara ke dunia iblis, Staz tidak sabar untuk bertemu dengan manusia dan mempelajari semua yang dia bisa tentang dunianya. Sayangnya, sebelum dia dapat menanyakan apa pun padanya, gadis itu dibunuh oleh salah satu calon perampasnya, hanya meninggalkan jiwanya yang telanjang. Staz bersumpah untuk membantu gadis itu memulihkan tubuhnya dan kembali ke kehidupan sebelumnya — terutama karena itu berarti melakukan perjalanan ke dunia manusia sendiri!',
                "tahun_rilis" => "2009",
                "penerbit" => "Young Ace",
                "rating" => "7.92",
                "status" => "Tamat"
            ],
            [
                "judul" => "Akame ga Kill",
                "slug" => "akame-ga-kill",
                "penulis" => "Tetsuya Tashiro & Takahiro",
                "sampul" => "https://i.pinimg.com/originals/37/0d/b8/370db87083606d66ee4ce526f23620fd.jpg",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => 'Bercerita tentang Dalam dunia fantasi, pejuang Tatsumi berangkat ke Ibukota untuk mendapatkan uang untuk desanya yang kelaparan, dan menemukan dunia korupsi yang tak terbayangkan, semuanya menyebar dari Perdana Menteri yang bejat yang mengendalikan telinga anak Kaisar. Setelah hampir menjadi korban dari korupsi ini sendiri, Tatsumi direkrut oleh Night Raid, sekelompok pembunuh yang didedikasikan untuk menghilangkan korupsi yang mengganggu Capitol dengan tanpa ampun membunuh mereka yang bertanggung jawab.',
                "tahun_rilis" => "2010",
                "penerbit" => "Gangan Joker (Square Enix)",
                "rating" => "7.96",
                "status" => "Tamat"
            ],
            [
                "judul" => "Eden's Zero",
                "slug" => "edens-zero",
                "penulis" => "Hiro Mashima",
                "sampul" => "https://static.wixstatic.com/media/dde27e_c445420a80e441b3be6a1f87c5e97f73~mv2.png/v1/fill/w_1000,h_1778,al_c,usm_0.66_1.00_0.01/dde27e_c445420a80e441b3be6a1f87c5e97f73~mv2.png",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => "Eden's Zero, sebuah komik fantasy dimana robot memiliki kesadaran layaknya manusia. Rebecca, seorang gading yang berpetualang suatu hari sampai di sebuah kerajaan bernama Kerajaan Granbell. Sudah 100 tahun sejak manusia terakhir datang di kerajaan tersebut. Hampir semua penduduk dikerajaan itu adalah robot, kecuali seorang anak bernama Shiki. Suatu hari, semua robot di kerajaan Grandbell berniat untuk membunuh Rebecca, apakah yang akan terjadi berikutnya?",
                "tahun_rilis" => "2018",
                "penerbit" => "Shuukan Shounen Magazine",
                "rating" => "9.03",
                "status" => "Belum Tamat"
            ],
            [
                "judul" => "ZIPMAN!!",
                "slug" => "zipman",
                "penulis" => "Shibata, Yuusaku (Story & Art)",
                "sampul" => "https://pbs.twimg.com/media/EKSoteIUEAY3ETd.jpg",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => "Insinyur mekanik tampan yang terkenal di dunia Koshiro Tatara dan Kaname Musclehead yang tampak menakutkan, si kembar yang berseberangan ini jatuh cinta pada senyum gadis yang sama. Sejak itu, mereka berkompetisi setiap hari untuk melihat siapa di antara mereka yang bisa membuatnya lebih tersenyum. Tapi suatu hari, tragedi tiba-tiba menyerang Koshiro...apa yang terjadi, dan bagaimana kelanjutannya ikuti terus serinya di mangaku.in yang akan selalu memanjakan kalian dengan serial komik terbaik dan terbaru",
                "tahun_rilis" => "2019",
                "penerbit" => "Shounen Jump",
                "rating" => "7.94",
                "status" => "Belum Tamat"
            ],
            [
                "judul" => "Pseudo Harem",
                "slug" => "pseudo-harem",
                "penulis" => "Saitou Yuu",
                "sampul" => "https://avt.mkklcdnv6temp.com/40/f/16-1583494908.jpg",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => "Kisah Nanakura Rin dari Klub Drama, yang memiliki bakat tak terbantahkan sebagai aktris, dan senpainya di klub yang sama, Kitahama Eiji. Dengan kekuatan aktingnya, Rin menggoda Eiji dengan berbagai persona, memberinya harem yang selalu dia impikan!",
                "tahun_rilis" => "2018",
                "penerbit" => "-",
                "rating" => "7.87",
                "status" => "Tamat"
            ],
            [
                "judul" => "7th Garden",
                "slug" => "7th-garden",
                "penulis" => "Mitsu Izumi",
                "sampul" => "https://cover.komiku.id/wp-content/uploads/Komik-7th-Garden.jpg?w=225&quality=60",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => "Bercerita tentang Sebagai seorang tukang kebun yang bertugas di sebuah rumah pedesaan, Avin berharap tidak lebih dari hari-hari damai bersama putri tuannya, Marie. Suatu hari, dia tidak sengaja membangunkan setan yang tidur di gunung terdekat. Apa yang dia inginkan adalah menjadikannya sebagai pelayan sebelum menjatuhkan surga dan mengubah dunia ini menjadi kebunnya. Avin tentu saja menolak tawaran itu. Namun, tidak lama setelah itu, kota tempat tinggal Avin tiba-tiba digerebek oleh Ksatria Templar yang seharusnya melindungi negara. Avin kemudian dihadapkan dengan pilihan: Apakah ia akan binasa bersama dengan taman dan orang-orang yang disayanginya, atau menjadi pelayan iblis dan menjadikan dunia ini binasa sebagai gantinya ...",
                "tahun_rilis" => "2014",
                "penerbit" => "Jump SQ",
                "rating" => "7.44",
                "status" => "Belum Tamat"
            ],
            [
                "judul" => "Vagabond",
                "slug" => "vagabond",
                "penulis" => "Inoue Takehiko & Yoshikawa Eiji & Inoue Takehiko",
                "sampul" => "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1615870877l/57429506._SX318_.jpg",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => "Tumbuh di era Sengoku abad ke-16 akhir Jepang, Shinmen Takezou dijauhi oleh penduduk desa setempat sebagai anak setan karena sifatnya yang liar dan kejam. Lari dari rumah bersama seorang bocah lelaki pada usia 17, Takezo bergabung dengan tentara Toyotomi untuk melawan klan Tokugawa di Pertempuran Sekigahara. Namun, Tokugawa memenangkan kemenangan besar, yang mengarah ke hampir tiga ratus tahun pemerintahan Shogun. Takezo dan temannya berhasil selamat dari pertempuran dan kemudian bersumpah untuk melakukan hal-hal besar dengan hidup mereka. Namun, setelah jalan mereka terpisah, Takezo menjadi penjahat yang dicari dan harus mengubah nama dan sifatnya untuk melarikan diri dari kematian tercela.",
                "tahun_rilis" => "1998",
                "penerbit" => "N/A",
                "rating" => "9.1",
                "status" => "Belum Tamat"
            ],
            [
                "judul" => "Vigilante: Boku no Hero Academia Illegal",
                "slug" => "vigilante-boku-no-hero-academia-illegal",
                "penulis" => "Betten Court & Furuhashi Hideyuki",
                "sampul" => "https://www.nautiljon.com/images/galerie/14/48/boku_no_hero_academia_1176784.jpg",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => 'Manga Vigilante: Boku no Hero Academia Illegal berceritatentang Di dunia di mana 80 persen populasi memiliki kekuatan super, "Pahlawan" adalah yang terpilih, dirayakan dan diberi wewenang untuk menggunakan kekuatan bawaan mereka untuk melayani masyarakat. Tapi tidak semua orang bisa mendapatkan atau diberi gelar Pahlawan, dan mereka yang menggunakan kekuatan mereka tanpa persetujuan masyarakat untuk melawan kejahatan dikenal dengan nama lain — Vigilantes!',
                "tahun_rilis" => "2016",
                "penerbit" => "Jump GIGA",
                "rating" => "9.06",
                "status" => "Belum Tamat"
            ],
            [
                "judul" => "World Of Immortals",
                "slug" => "world-of-immortals",
                "penulis" => "Charismatic Manga & Lara Lala",
                "sampul" => "https://cover.komiku.id/wp-content/uploads/Komik-World-Of-Immortals.jpg?w=225&quality=60",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => 'Berdasarkan novel ringan World Of Immortals yang sangat populer. Dunia Abadi, itu adalah dunia yang dirindukan setiap manusia. Bagi banyak orang, itu adalah kemuliaan abadi untuk menyebabkan distorsi spasial dan memasuki Dunia Dewa. Tetapi perubahan waktu hanyalah tanpa ampun, legenda tentang keabadian telah lama dilupakan. Namun, keajaiban akan muncul sekali lagi! Seorang abadi akan membagi ruang dengan seni bela diri dan memutuskan semua hubungan dengan dunia fana. Sang protagonis, Xiao Chen, terperangkap di dalamnya dan secara tidak sengaja dibawa ke Dunia Dewa. Apa yang akan mereka temukan di dunia luas di luar keretakan?',
                "tahun_rilis" => "2019",
                "penerbit" => "-",
                "rating" => "7.8",
                "status" => "Belum Tamat"
            ],
            [
                "judul" => "UQ Holder!",
                "slug" => "uq-holder",
                "penulis" => "Ken Akamatsu",
                "sampul" => "https://cdn.myanimelist.net/images/anime/6/88354.jpg",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => 'Bercerita tentang Dalam dekade sejak dunia menjadi sadar akan keberadaan sihir, dunia telah mengalami pergolakan besar. Namun, seorang anak bernama Touta tinggal di pengasingan di kota pedesaan jauh dari perubahan ini. kehidupan biasa nya disorot oleh sihir menggunakan guru perempuan dan teman-teman yang mendukung nya. Ketika hidup tenang sehari-hari terganggu, ia memulai pada petualangan yang unik.',
                "tahun_rilis" => "2013",
                "penerbit" => "Bessatsu Shounen Magazine",
                "rating" => "8.75",
                "status" => "Belum Tamat"
            ],
            [
                "judul" => "666 Satan",
                "slug" => "666-satan",
                "penulis" => "Kishimoto Seishi",
                "sampul" => "https://i.pinimg.com/originals/97/4d/20/974d209f1b6e5cf11a9b26c084c866e3.jpg",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => 'Dalam waktu yang tidak terlalu lama, umat manusia bertempur memperebutkan O-Parts, peninggalan dari peradaban kuno. Dibutuhkan jenis orang khusus untuk membuka potensi penuh dari sisa-sisa masa lalu ini, dan jenis manusia unik yang dikenal sebagai O.P.T.s (atau O-Parts Tacticians) menjadi kekuatan yang harus diperhitungkan. Sayangnya, O-Parts dapat digunakan untuk tujuan baik atau jahat. Jio adalah seorang anak muda dengan masa lalu yang tragis yang hanya mempercayai satu hal di dunia ini: uang. Sedikit yang dia curigai bahwa dia sebenarnya adalah O.P.T. yang sangat kuat, dan di dalam dirinya tidur setan dengan keganasan yang luar biasa. Dia bertemu dengan seorang gadis bernama Ruby, dan bersama-sama mereka memutuskan untuk memulai pencarian berbahaya untuk menemukan O-Parts sebanyak yang mereka bisa. Akankah Jio membantu Ruby mewujudkan mimpinya menjadi pemburu harta karun yang terkenal di dunia? Lebih penting lagi, apakah Ruby akan membantu Jio mewujudkan mimpinya - dominasi dunia ?!',
                "tahun_rilis" => "2001",
                "penerbit" => "Shounen Gangan",
                "rating" => "7.66",
                "status" => "Tamat"
            ],
            [
                "judul" => "Hahasama no Ie – Ogamiya Gounai Kokoro Hitomi no Kaiitan",
                "slug" => "hahasama-no-ie-ogamiya-gounai-kokoro-hitomi-no-kaiitan",
                "penulis" => "Takeda Itsuka & Kouchi Hitomi",
                "sampul" => "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx107548-WDaf8d8vJ2QB.jpg",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => 'Puluhan ribu, atau ratusan ribu. Itulah kemungkinan profesi penyembah benar-benar menjumpai hal yang aneh. Buatlah karya yang benar-benar lucu yang telah dinilai tinggi sebagai puncak tertinggi dari kisah hantu kisah nyata! Sebuah misteri menakjubkan yang dialami oleh penulis asli yang menjalankan toko ibadah di Tohoku!',
                "tahun_rilis" => "2020",
                "penerbit" => "-",
                "rating" => "6.0",
                "status" => "Belum Tamat"
            ],
            [
                "judul" => "Fairy Tail: 100 Years",
                "slug" => "fairy-tail-100-years-quest",
                "penulis" => "Hiro Mashima",
                "sampul" => "https://www.animenewsnetwork.com/hotlink/images/encyc/A22691-2293366365.1573545522.jpg",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => 'Setelah mengatasi ancaman Acnologia dan Zeref, Fairy Tail sudah menjadi lebih kuat dan lebih energik! Quest 100 tahun yang ditinggalkan Natsu dan kawan-kawann, dan juga kepada para anggota tetap di guild, sesuatu yang baru akan terjadi!? Meskipun cerita ini seharusnya sudah selesai, petualangan baru sekarang dimulai!',
                "tahun_rilis" => "2018",
                "penerbit" => "Magazine Pocket",
                "rating" => "8.92",
                "status" => "Belum Tamat"
            ],
            [
                "judul" => "Jagaaaaaan",
                "slug" => "jagaaaaaan",
                "penulis" => "Hiro Mashima",
                "sampul" => "https://www.anime-planet.com/images/manga/covers/thumbs/nano-hazard-32753.jpg?t=1548711175",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => 'Shintarou Jagasaki adalah seorang polisi yang memiliki angan-angan menembak semua penjahat, tapi hanya sebatas angan-angan. tiba-tiba ada virus kodok yang bisa membuat manusia menjadi seorang monster menyeramkan, lalu ketika ada seorang yang berubah menjadi monster jagasaki tiba-tiba juga mendapatkan kekuatan bisa menembak dari tangan kanan sampai-sampai mampu menghancurkan tubuh monster tersebut. Bagaimanakah petualangan jagasaki dalam membasmi para monster itu mari kita simak bersama.',
                "tahun_rilis" => "2018",
                "penerbit" => "Big Comic Spirits (Shogakukan)",
                "rating" => "8.99",
                "status" => "Belum Tamat"
            ],
            [
                "judul" => "Dragon Ball Super",
                "slug" => "dragon-ball-super",
                "penulis" => "Akira Toriyama & Toyble",
                "sampul" => "https://upload.wikimedia.org/wikipedia/id/7/74/Dragon_Ball_Super_Key_visual.jpg",
                "created_at" => Time::now(),
                "updated_at" => Time::now(),
                "sinopsis" => 'Setelah Majin Boo dikalahkan, bumi kembali damai dan Goku bercocok tanam di sekitar kediamannya. Sanak keluarganya pun menikmati keadaan damai tersebut dengan melakukan aktivitas masing-masing. Seperti biasa, serial Dragon Ball bukanlah bertema drama melainkan anime aksi, jadinya akan ada ancaman baru yang mengarah ke bumi tempat mereka tinggal. Kali ini datang dari sosok yang bernama Beerus, God of Destruction. Beerus boleh dikatakan sosok menakutkan dan kuat di galaksi “Dragon Ball“. Dia berniat melawan ksatria legenda yang terlihat dalam sebuah ramalan yang dikenal sebagai Super Saiyan God.',
                "tahun_rilis" => "2015",
                "penerbit" => "V Jump (Shueisha)",
                "rating" => "8.75",
                "status" => "Belum Tamat"
            ],
        ];
        $this->db->table("komikmanga")->insertBatch($data);
    }
}
